[build]
  command = "npm run build"
  publish = "dist/public"
  
[build.environment]
  NODE_VERSION = "20"

# Handle SPA routing for client-side routing with wouter
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200